<!DOCTYPE html>
<html lang="th">
<head>
  <meta charset="UTF-8">
  <title>Aumbid</title>
  <style>
    body {
      margin: 0;
      font-family: 'Kanit', sans-serif;
      background: linear-gradient(135deg, #111, #000);
      color: white;
      text-align: center;
    }

    header {
      padding: 30px 0;
      background-color: #ffcc00;
      color: #000;
      font-size: 2em;
      font-weight: bold;
      box-shadow: 0 0 20px #ffff33;
      position: relative;
    }

    .lightning-icon {
      position: absolute;
      top: 10px;
      left: 20px;
      font-size: 40px;
      color: #fff700;
      text-shadow: 0 0 10px yellow;
    }

    .income-container {
      margin-top: 80px;
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 20px;
    }

    .income-box {
      background-color: #222;
      border: 2px solid #ffd700;
      padding: 30px 40px;
      border-radius: 15px;
      box-shadow: 0 0 20px #ffeb3b33;
      width: 80%;
      max-width: 500px;
    }

    .income-title {
      font-size: 1.8em;
      margin-bottom: 15px;
      color: #ffe600;
      text-shadow: 0 0 10px #fff000;
    }

    .income-amount {
      font-size: 2.5em;
      font-weight: bold;
      color: #00ffcc;
      text-shadow: 0 0 10px #00ffe0;
    }

    .footer {
      margin-top: 60px;
      color: #888;
      font-size: 0.9em;
    }

    .back-button {
      margin-top: 30px;
      background: linear-gradient(145deg, #ffe600, #ffc400);
      color: #000;
      border: none;
      padding: 15px 30px;
      font-size: 1.2em;
      font-weight: bold;
      border-radius: 12px;
      box-shadow: 0 0 15px #ffff33;
      cursor: pointer;
      transition: 0.3s;
      text-decoration: none;
      display: inline-block;
    }

    .back-button:hover {
      background: #fff200;
      box-shadow: 0 0 25px #fff933, 0 0 50px #fff933;
      transform: scale(1.05);
    }
  </style>
</head>
<body>

  <header>
    <span class="lightning-icon">⚡</span>
    รายได้
  </header>

  <div class="income-container">
    <div class="income-box">
      <div class="income-title">รายได้ทั้งหมด</div>
      <div class="income-amount">80</div>
    </div>

    <a href="https://nete11.github.io/" class="back-button">⬅ กลับหน้าเมนูหลัก</a>
  </div>

  <div class="footer">
    © 2025 Aumbid | Design by nerdสุดหล่อ
  </div>

</body>
</html>
